export * as chapter1 from "./Chapter1/index"
export * as chapter2 from "./Chapter2/index"
export * as chapter3 from "./Chapter3/index"
export * as chapter4 from "./Chapter4/index"
export * as chapter5 from "./Chapter5/index"
export * as chapter6 from "./Chapter6/index"