export enum Language
{
    None = 'none',
    // Brazilian = 'brazilian',
    // Bulgarian = 'bulgarian',
    // Czech = 'czech',
    // Danish = 'danish',
    English = 'english',
    // Finnish = 'finnish',
    // French = `french`,
    // German = `german`,
    // Greek = 'greek',
    // Hungarian = 'hungarian',
    // Italian = 'italian',
    // Japanese = 'japanese',
    // Koreana = 'koreana',
    // Latam = 'latam',
    // Norwegian = `norwegian`,
    // Polish = 'polish',
    // Portuguese = `portuguese`,
    Russian = `russian`,
    Schinese = `schinese`,
    // Spanish = `spanish`,
    // Swedish = `swedish`,
    // TChinese = `tchinese`,
    // Thai = 'thai',
    // Turkish = 'turkish',
    // Ukrainian = 'ukrainian',
    // Vietnamese = `vietnamese`
}
